url: "https://tastucnakem.cz/"
title: Ta s tučňákem
favicon: /img/favicon.png
language: cs
author: Veronika Burgerová
keywords: TODO
description: Veronika Burgerová a její tučňáci
about: Knihomolka Veranda.
robots: index,follow
google_analytics: UA-XXXXXXXX-Y

permalink: pretty
include: ["_pages", ".htaccess"]

social:
    - icon: fa-instagram
      link: "#"
    - icon: fa-facebook
      link: "#"

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
  - old
